name: 3d-graph-plotter
version: '1.0'
summary: |
  Application for Mind Mapping, Knowledge
  and Project Management
description: |
  3d-graph-plotter is a free and open source project that is used to draw 3d grphs
  of functions. Explicit functions , implicit functions and parametric functions can
  be drawn. Multiple graphs can be plotted in a single space. 

confinement: devmode

parts:
  freeplane:
    after: [desktop-glib-only]
    plugin: gradle
    source: .
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      gradle release -x test -x createGitTag
    install: |
      unzip DIST/3d-graph-plotter_bin-*.zip -d \
      $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip
      - openjdk-8-jdk

apps:
  freeplane:
    command: desktop-launch \
      $SNAP/3d-graph-plotter-1.0/3d-graph-plotter.sh
